import { Geist, Geist_Mono, Inter } from "next/font/google";
import "./globals.css";
import { Footer } from "@/components/constants/Footer";
import Navbar from "@/components/constants/Navbar";
import { GoToTop } from "@/components/constants/GoToTop";
import ProtectedComponent from "@/components/ProtectedComponent";

const inter = Inter({
  variable: "--font-inter",
  weight: ["100", "200", "300", "400", "500", "600", "700", "800", "900"],
  subsets: ["latin"],
});

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body className={`${inter.variable} antialiased bg-black`}>
        <ProtectedComponent>{children}</ProtectedComponent>
      </body>
    </html>
  );
}
